include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - avoid_dynamic_calls
    - avoid_relative_lib_imports
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_locals
    - prefer_single_quotes
    - require_trailing_commas
    - unawaited_futures
    - unnecessary_await_in_return
    - use_super_parameters

analyzer:
  errors:
    missing_return: error
    dead_code: warning
    unused_import: warning
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
